route:
  receiver: 'database_writer'
  routes:
  - match:
      severity: critical
    receiver: 'critical_team'

receivers:
- name: 'database_writer'
  webhook_configs:
  - url: 'http://webhook:5000/alerts'
  
- name: 'critical_team'
  email_configs:
  - to: 'sre@allinai.com' 