- name: 启动服务
  win_service:  # Windows
    name: "{{ service_name }}"
    state: started
  when: ansible_os_family == 'Windows'

- name: 启动服务
  systemd:  # Linux
    name: "{{ service_name }}"
    state: started
  when: ansible_os_family == 'Debian' 