services:
  ops_center:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000" 